### ISSUE TITLE
[BUG] does not set the initial state

### ISSUE THREAD

**Issue by Tuhaj** [state-machines/state_machines#16] opened 2015-04-24 14:02 UTC
I'm almost certain it is a bug.
Please tell me if I'm wrong. The initial state should be set, but it stays nil.
Here is a test for this: 

https://gist.github.com/Tuhaj/fd40fd1a088779c70333

**Comment by imanel** [comment] 2015-04-24 16:27
What you need is [state_machines-activerecord](https://github.com/state-machines/state_machines-activerecord). After changing lines 5 and 20 of your script to `state_machines-activerecord` the test will pass.

It might be good idea to mention such requirement in Readme as it might not be obvious for some users.

**Comment by pboling** [comment] 2015-04-24 18:48
I don't know how this happens, but we also just switched to the state_machines gem, and we started by just listing `state_machines-activerecord` in our Gemfile.  It **did not** pull the `state_machines` gem into our gemfile.  It doesn't make any sense.

* state_machines-activemodel [requires state_machines here](https://github.com/state-machines/state_machines-activemodel/blob/master/state_machines-activemodel.gemspec#L20) 
* state_machines-activerecord [requires state_machines here](https://github.com/state-machines/state_machines-activerecord/blob/master/state_machines-activerecord.gemspec#L20)

But this absolutely did not happen for us.  Perhaps there is a difference in the released versions?

**Comment by pboling** [comment] 2015-04-24 18:51
Also after the switch we did get a massive amount of spec failures, and it does look like the non-support of initial states via factory girl, as mentioned in the Readme, may be at fault for us.

**Comment by pboling** [comment] 2015-04-24 19:05
I have this in my Gemfile:
```
  gem 'state_machines'
  gem 'state_machines-activerecord'
```
And I ran this:
```
bundle update state_machines-activerecord
```
And got nothing:
```
Using state_machines 0.2.2
Using state_machines-activerecord 0.0.0
```
Using state_machines 0.2.2
Using state_machines-activerecord 0.0.0

**Comment by pboling** [comment] 2015-04-24 19:23
This is getting stranger by the minute.  I added `gem state_machines-activemodel` to our Gemfile, and then ran `bundle install`, and got:
```
Using state_machines 0.2.2
Installing state_machines-activemodel 0.0.2
Using state_machines-activerecord 0.0.0
```

???

**Comment by imanel** [comment] 2015-04-24 20:23
`state_machines-activerecord` was the only release that [did not specified any dependencies](https://rubygems.org/gems/state_machines-activerecord/versions/0.0.0). I believe it's by mistake as [readme states that Rails 4.1+ is required](https://github.com/state-machines/state_machines-activerecord) (so it might not work at all with 3.2)

**Comment by pboling** [comment] 2015-04-24 20:31
Yep, it does not work well, many spec failures in our suite.  We have switched to `seuros/state_machine` and are trying that.

**Comment by agis-** [comment] 2015-07-23 12:02
@pboling Any insight into what actually works with Rails 3.2 apps that want to migrate away from the unmaintained *state_machine* gem?

Does `seuros/state_machine` does the trick?

**Comment by pboling** [comment] 2015-07-23 17:34
@agis- unfortunately we were not on the latest of the old `state_machine`, 1.2.0.  If you were on 1.2.0 the seuros fork would, I think, work for you.

We are on 1.1.2, and we rely on some of the bugs of 1.1.2, which were breaking changes / fixes in 1.2.0, so our upgrade path is very rocky.

**Comment by agis-** [comment] 2015-07-23 17:45
@pboling Fortunately, I'm on 1.1.2 and in the process of upgrading to Rails 4.2.

**Comment by pboling** [comment] 2015-07-23 17:53
Did you mean 1.2.0?  I don't know of any clean upgrade path from 1.1.2.  You might need to upgrade to old 1.2.0 first, but that can be a pain in the ass.

**Comment by agis-** [comment] 2015-07-23 17:59
I'm currently in Rails 3.2 and `state_machine` 1.1.2. I'm in the process of upgrading to Rails 4.0 and on. I've noticed that there are certain issues with the unmaintained `state_machine` gem and looking for an upgrade path to Rails 4.0 and later, whether it involves upgrading to `state_machine` 1.2.0 or going to an alternative fork.

AFAICT there's not a clear upgrade path yet. I will probably try going to 1.2.0 and then @seuros fork. I've also tried `state_machines` but it also [has bugs](https://github.com/state-machines/state_machines/issues/14#issuecomment-124075398).

**Comment by pboling** [comment] 2015-07-23 18:10
The new state_machines gem works great, but only if you are on Rails 4.2.  So switch to that once you get there, as it is maintained.

The upgrade path is this:
* state_machine 1.1.2 (you, and me, now), rails 3.2
* state_machine 1.2.0, rails 3.2
* seuros/state_machine fork of state_machine, rails 3.2
* seuros/state_machine fork of state_machine, rails 4.2 (and any other rails steps you may need to get from 3.2 to 4.2)
* new state_machines gem, rails 4.2

**Comment by agis-** [comment] 2015-07-23 18:23
Cool, will try that.

Thanks!

**Comment by pboling** [comment] 2015-07-23 18:27
Please report back if it does / does not work.  I will be doing the same at some point, and that guide is my plan to follow, and it *should* work.

**Comment by agis-** [comment] 2015-07-23 18:30
Will do. However I have a long road yet.

**Comment by agis-** [comment] 2015-08-05 08:24
@pboling Moved straight to seuros/state_machine (at https://github.com/seuros/state_machine/commit/95ba53f03e5657a5873343c2b1dc6a148ea3542e) from state_machine 1.1.2 in our Rails 3.2.22 app and everything is fine.

**Comment by rosskevin** [comment] 2015-08-05 14:55
Closing because this looks like it is _not a bug_ for state_machines as state_machines is intended to work for rails 4.x and above.  This looks like useful information though re: migration from the old gem.  If @agis- or @pboling would like to add a wiki page based on your path to 4.x, it could be helpful to others.

**Closed by rosskevin** 2015-08-05 14:55 UTC
